from config.settings_class import *

DIFFICULTY = 2
SCORE = 0
LIVES = 3
NO_OF_BALLS = 1
BRICK_SIZE = 100
BRICK_TYPE = 1
FPS = 90
BRICKS_REMAINING = 0
CURRENT_LVL = 0
NR_OF_LVL = 2

SETTINGS_OBJ = Settings(DIFFICULTY, SCORE, LIVES, NO_OF_BALLS, BRICK_SIZE, BRICK_TYPE, FPS, BRICKS_REMAINING, CURRENT_LVL, NR_OF_LVL)
